# Generated by Django 5.2.3 on 2025-06-12 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('body', models.TextField(verbose_name='corpo')),
                ('is_premium', models.BooleanField(default=False, verbose_name='é premium')),
                ('created_at', models.DateTimeField(verbose_name='criado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='criado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_posts', to=settings.AUTH_USER_MODEL, verbose_name='publicado por')),
            ],
            options={
                'verbose_name': 'Postagem do Blog',
                'verbose_name_plural': 'Postagens do Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
