# Generated by Django 5.2.3 on 2025-06-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
    ]
